import { UserProfile } from "@/types";

export const DUMMY_USERS: UserProfile[] = [
  {
    id: "student_1",
    name: "佐藤 拓海",
    email: "sato.takumi@univ.ac.jp",
    role: "student",
    department: "情報工学科3年",
    avatar: "👨‍🎓",
    topics: ["履修登録", "研究室選び"],
    availableTimesFreeText: "木曜と金曜の午前中が空いています。",
    avoidTimesFreeText: "月曜日は講義が詰まっているため避けたいです。",
    absoluteNGTimes: ["Monday-Morning", "Monday-Afternoon"],
    mailPolicy: "丁寧なやり取りを心がけます。",
    mailRequiredInfo: [],
  },
  {
    id: "prof_suzuki",
    name: "鈴木 茂 教授",
    email: "suzuki.shigeru@univ.ac.jp",
    role: "professor",
    department: "情報工学科 (計算機アーキテクチャ研究室)",
    avatar: "👨‍🏫",
    topics: ["研究室選び", "卒論指導", "計算機システム", "進路相談"],
    availableTimesFreeText: "金曜日の午前中（9:00〜12:00）は比較的空いています。",
    avoidTimesFreeText: "水曜日は終日、学内会議や外部審査があるためできれば避けてください。",
    absoluteNGTimes: ["Wednesday-All", "Saturday-All", "Sunday-All"],
    mailPolicy: "アポイント前に必ずメールで具体的な相談内容を送ってください。",
    mailRequiredInfo: ["学籍番号", "氏名", "相談したい具体的なテーマ（3行程度）"],
    generalNotes: "対面での面談は研究室（3号館4階）で行います。オンライン（Zoom）も対応可能です。",
  },
  {
    id: "prof_takahashi",
    name: "高橋 美咲 准教授",
    email: "takahashi.misaki@univ.ac.jp",
    role: "professor",
    department: "情報工学科 (知能情報システム研究室)",
    avatar: "👩‍🏫",
    topics: ["研究室選び", "履修登録", "AI・データサイエンス", "女子学生サポート"],
    availableTimesFreeText: "木曜日の午後（13:00〜17:00）が面談枠として確保しやすいです。",
    avoidTimesFreeText: "月曜日の午前中は週次ミーティングがあるため避けてほしいです。また、メールで解決する用件（申請書の承認など）であれば、面談ではなくメール添付で送ってください。",
    absoluteNGTimes: ["Monday-Morning", "Saturday-All", "Sunday-All"],
    mailPolicy: "メールで済む内容ならメールで完結させたいです。面談希望の場合は、その理由を書いてください。",
    mailRequiredInfo: ["学籍番号", "面談が必要な理由"],
    generalNotes: "1回の面談は原則30分以内とさせてください。メールで書類やり取りができる場合は、そちらを最優先してください。",
  },
  {
    id: "office_career",
    name: "キャリアセンター (進路支援課)",
    email: "career-support@univ.ac.jp",
    role: "staff",
    department: "学生支援本部",
    avatar: "🏢",
    topics: ["進路相談", "就職活動", "履歴書添削", "模擬面接", "インターンシップ"],
    availableTimesFreeText: "平日の窓口時間（9:00〜17:00）であれば柔軟に対応可能です。",
    avoidTimesFreeText: "12:00〜13:00の昼休み時間帯は窓口が混雑するため避けてください。",
    absoluteNGTimes: ["Saturday-All", "Sunday-All", "Weekday-Night"],
    mailPolicy: "予約内容の確認、またはオンライン面談のURL送付のために連絡します。事前相談シートの提出が必要です。",
    mailRequiredInfo: ["学籍番号", "氏名", "相談希望分野（就職 / 進学 / インターン等）", "添削希望の有無"],
    generalNotes: "対面相談はA棟1階のキャリアセンターで実施します。履歴書添削を希望する場合は、Wordファイルをメールに添付するか印刷して持参してください。",
  },
  {
    id: "ta_tanaka",
    name: "田中 健太 (大学院TA)",
    email: "tanaka.kenta@stud.univ.ac.jp",
    role: "ta",
    department: "情報工学専攻 博士前期課程2年",
    avatar: "🧑‍💻",
    topics: ["プログラミング質問", "講義の課題", "研究室の日常", "院試対策"],
    availableTimesFreeText: "月曜・火曜の放課後（16:30以降）や、土日のオンラインでも対応可能です。",
    avoidTimesFreeText: "水曜と木曜は自身の研究発表準備のため、急ぎでない限り避けてもらえると助かります。",
    absoluteNGTimes: ["Wednesday-Morning", "Thursday-Morning"],
    mailPolicy: "Slackやメールで気軽に質問して構いません。件名に【TA質問】と入れてください。",
    mailRequiredInfo: ["氏名", "講義名", "エラーコードや質問のスクリーンショット（ある場合）"],
    generalNotes: "主にプログラミング演習（C言語, Python）のサポートをします。対面は水曜以外の平日夕方に演習室にいます。",
  }
];

// 初期選択用などのダミー相談カテゴリ
export const DUMMY_TOPICS = [
  "研究室選び",
  "履修登録",
  "進路相談",
  "就職活動",
  "履歴書添削",
  "卒論指導",
  "プログラミング質問",
  "講義の課題",
  "その他"
];
